apiVersion : apps/v1
kind: Deployment
metadata:
  name: webhttptest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhttptest
  template:
    metadata:
      labels:
        app: webhttptest 
    spec:
      containers:
        - name: webhttptest 
          image: davidxw/webtest:latest
          ports:
          - containerPort: 80
          resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m
