apiVersion: v1
kind: Service
metadata:
    name: webhttptest
    annotations:
        service.beta.kubernetes.io/azure-dns-label-name: webhttptest
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: webhttptest